### ISSUE TITLE
SpannerJDBC: grpc netty libraries are not shaded fully which result in service load runtime errors

### ISSUE THREAD

**Issue by yunus** [googleapis/java-spanner-jdbc#516]
#### Environment details

1. Spanner JDBC
2. OS type and version: MacOS
3. Java version: 8
4. spanner-jdbc version(s): master

#### Steps to reproduce
This error happens when there are multiple `io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider` implementations in the classpath. In my case, there are two uber-jars one is Spanner JDBC and another internal library which is again an uber-jar. 
I have also tested with shaded Spanner JDBC and direct addition of _io.grpc:grpc-netty-shaded:1.38.1_ to classpath.

As you see in the stack trace below _NettyChannelProvider_ should be a subtype of _ManagedChannelProvider_, which is true if we only have Spanner JDBC uber jar. I have decompiled _NettyChannelProvider_ and see that it extends _com.google.cloud.spanner.jdbc.shaded.io.grpc.ManagedChannelProvider_.
However, when there is another implementation of _NettyChannelProvider_ in the classpath which is the original, it extends _io.grpc.ManagedChannelProvider_. As a result, JRE may load the wrong NettyChannelProvider and hence we see the error.

#### Code example
My solution is relocating netty as well. But relocating under `io` group results in errors (and also ugly) since `io` is named twice inside netty library: `io.grpc.netty.shaded.io.grpc` and double relocation happens.
I have tried several relocation patterns and till now only this one worked for me. I am not sure it is bullet proof.

With the below relocation, i don't encounter any errors.

```java
<relocation>
  <pattern>io.</pattern>
  <shadedPattern>com.google.cloud.spanner.jdbc.shaded.io.</shadedPattern>
  <excludes>
    <exclude>io.grpc.netty.shaded.**</exclude>
  </excludes>
</relocation>
<relocation>
  <pattern>io.grpc.netty.shaded.io.</pattern>
  <shadedPattern>com.google.cloud.spanner.jdbc.shaded.io.grpc.netty.shaded.io.</shadedPattern>
</relocation>
```

#### Stack trace
```
Caused by: java.util.ServiceConfigurationError: com.google.cloud.spanner.jdbc.shaded.io.grpc.ManagedChannelProvider: Provider io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider not a subtype
        at java.util.ServiceLoader.fail(ServiceLoader.java:239)
        at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at com.google.cloud.spanner.jdbc.shaded.io.grpc.ServiceProviders.loadAll(ServiceProviders.java:67)
        at com.google.cloud.spanner.jdbc.shaded.io.grpc.ManagedChannelRegistry.getDefaultRegistry(ManagedChannelRegistry.java:96)
        at com.google.cloud.spanner.jdbc.shaded.io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:41)
        at com.google.cloud.spanner.jdbc.shaded.io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
```

**Comment by thiagotnunes** [comment]
@olavloite Could you help out with this? Thanks!

**Comment by olavloite** [comment]
@yunus I'm a little wary of applying this change generically to the shaded build. I'm not sure it would work in all cases, and your use case seems to be quite specific with two different über-jars containing partly the same libraries. Is there a specific reason in this case why you cannot use the [Google Cloud Java BoM](https://github.com/googleapis/java-cloud-bom) instead of two separate über-jars?

**Comment by yunus** [comment]
To clarify, the error happens when I add a direct dependency for io.grpc:grpc-netty-shaded as well, it does not have to be inside another uber jar. I have tried many other relocation strategies but they have led to other issues. 

Anyway, I understand that this is a specific case. Let's park it here, maybe in the future others report similar issues with better solutions and we re-open this case.
