### ISSUE TITLE
spanner-jdbc: Unable to update dependency org.apache.commons:commons-lang3

### ISSUE THREAD

**Issue by skuruppu** [googleapis/java-spanner-jdbc#58]
PR #6 seems to be causing the following build failure:

```
[ERROR] Tests run: 6, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 2.255 s <<< FAILURE! - in com.google.cloud.spanner.jdbc.JdbcDatabaseMetaDataWithMockedServerTest
[ERROR] com.google.cloud.spanner.jdbc.JdbcDatabaseMetaDataWithMockedServerTest.getColumnsInDdlBatch  Time elapsed: 0.7 s  <<< ERROR!
java.lang.UnsupportedClassVersionError: org/apache/commons/lang3/ArrayUtils : Unsupported major.minor version 52.0
	at com.google.cloud.spanner.jdbc.JdbcDatabaseMetaDataWithMockedServerTest.getColumnsInDdlBatch(JdbcDatabaseMetaDataWithMockedServerTest.java:159)

[ERROR] com.google.cloud.spanner.jdbc.JdbcDatabaseMetaDataWithMockedServerTest.getIndexInfoInDdlBatch  Time elapsed: 0.372 s  <<< ERROR!
java.lang.UnsupportedClassVersionError: org/apache/commons/lang3/ArrayUtils
	at com.google.cloud.spanner.jdbc.JdbcDatabaseMetaDataWithMockedServerTest.getIndexInfoInDdlBatch(JdbcDatabaseMetaDataWithMockedServerTest.java:263)

[ERROR] com.google.cloud.spanner.jdbc.JdbcDatabaseMetaDataWithMockedServerTest.getSchemasInDdlBatch  Time elapsed: 0.334 s  <<< ERROR!
java.lang.UnsupportedClassVersionError: org/apache/commons/lang3/ArrayUtils
	at com.google.cloud.spanner.jdbc.JdbcDatabaseMetaDataWithMockedServerTest.getSchemasInDdlBatch(JdbcDatabaseMetaDataWithMockedServerTest.java:289)

[ERROR] com.google.cloud.spanner.jdbc.JdbcDatabaseMetaDataWithMockedServerTest.getTablesInDdlBatch  Time elapsed: 0.287 s  <<< ERROR!
java.lang.UnsupportedClassVersionError: org/apache/commons/lang3/ArrayUtils
	at com.google.cloud.spanner.jdbc.JdbcDatabaseMetaDataWithMockedServerTest.getTablesInDdlBatch(JdbcDatabaseMetaDataWithMockedServerTest.java:130)

[ERROR] com.google.cloud.spanner.jdbc.JdbcDatabaseMetaDataWithMockedServerTest.getKeysInDdlBatch  Time elapsed: 0.319 s  <<< ERROR!
java.lang.UnsupportedClassVersionError: org/apache/commons/lang3/ArrayUtils
	at com.google.cloud.spanner.jdbc.JdbcDatabaseMetaDataWithMockedServerTest.getKeysInDdlBatch(JdbcDatabaseMetaDataWithMockedServerTest.java:192)

[ERROR] com.google.cloud.spanner.jdbc.JdbcDatabaseMetaDataWithMockedServerTest.getCrossReferencesInDdlBatch  Time elapsed: 0.232 s  <<< ERROR!
java.lang.UnsupportedClassVersionError: org/apache/commons/lang3/ArrayUtils
	at com.google.cloud.spanner.jdbc.JdbcDatabaseMetaDataWithMockedServerTest.getCrossReferencesInDdlBatch(JdbcDatabaseMetaDataWithMockedServerTest.java:231)
```

@olavloite is this something that can be fixed in the tests?

**Comment by olavloite** [comment]
I could probably fix this specific issue, BUT: According to the [release notes](https://commons.apache.org/proper/commons-lang/changes-report.html#a3.9)  version 3.9 of commons-lang requires minimum Java 8. AFAIK, we officially still support Java 7. I can locally confirm that this broken on Java 7 but works on Java 8.

**Comment by skuruppu** [comment]
Thanks for checking @olavloite. We'll continue the discussion on which Java versions to support to figure out if we can drop support for Java 7.

**Comment by skuruppu** [comment]
I'm going to close this issue. Will reopen once we've made plans to drop support for Java 7.
