### ISSUE TITLE
NoClassDefFoundError for com.google.cloud.spanner.TimestampBound

### ISSUE THREAD

**Issue by SanjayVas** [googleapis/java-spanner-jdbc#939]
#### Environment details

1. OS type and version: Linux (gLinux Rodete based on Debian Bookworm)
1. Java version: JDK 11 via Kotlin JVM
1. version(s): google-cloud-spanner-jdbc 2.7.6, google-cloud-spanner 6.28.0

#### Steps to reproduce

  1. Attempt to get a connection via `DriverManager.getConnection` with a JDBC connection string

#### Code example

```kotlin
DriverManager.getConnection(connectionString).use { connection ->
  Liquibase.fromPath(connection, changelogPath).use { liquibase ->
    liquibase.update(Contexts())
  }
}
```

#### Stack trace
```
java.lang.NoClassDefFoundError: Could not initialize class com.google.cloud.spanner.TimestampBound
        at com.google.cloud.spanner.connection.ConnectionImpl.<init>(ConnectionImpl.java:213)
        at com.google.cloud.spanner.connection.ConnectionOptions.getConnection(ConnectionOptions.java:890)
        at com.google.cloud.spanner.jdbc.AbstractJdbcConnection.<init>(AbstractJdbcConnection.java:65)
        at com.google.cloud.spanner.jdbc.JdbcConnection.<init>(JdbcConnection.java:56)
        at com.google.cloud.spanner.jdbc.JdbcDriver.connect(JdbcDriver.java:196)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251
```

#### Any additional information below

Using library from Maven central. I don't get this error if I downgrade google-cloud-spanner-jdbc to 2.7.5 and google-cloud-spanner 6.27.0.

**Comment by rajatbhatta** [comment]
Hi @SanjayVas: Can you check if this issue got fixed with the latest version?

**Comment by SanjayVas** [comment]
Cannot reproduce the error with google-cloud-spanner 6.34.1 and google-cloud-spanner-jdbc 2.9.0

**Comment by rajatbhatta** [comment]
Thanks for confirming, @SanjayVas! Closing this issue.
